version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: web-search-mongodb-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - web-search-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  web-search-dev-network:
    driver: bridge
